### ISSUE TITLE
Generics order of EffectfulComponent

### ISSUE THREAD

**Issue by zimme** [motorcyclets/motorcycle#137]
Is there a reason that `Sinks` comes before `Sources` in the generics typing for this instead of the other way around? `Sources` seems to be first in "all" the other types.

**Comment by TylorS** [comment]
Hello @zimme thanks for your interest in Motorcycle!

The order of `EffectfulComponent` is to reflect that `Sinks` is the input and `Sources` is the output as opposed to a "regular" `Component` which has `Sources` as input and `Sinks` as output.

```typescript
import { run } from '@motorcycle/run'
import { Component, EffectfulComponent } from '@motorcycle/types'
import { DomSources, DomSinks, makeDomComponent } from '@motorcycle/mostly-dom'

const element = document.querySelector('#container')

const UI: Component<DomSources, DomSinks> = function UI(sources: Sources): Sinks {
  const { dom } = sources

  const view$ = //

  return { view $}
}

const Dom: EffectfulComponent<DomSinks, DomSources> = makeDomComponent(element)

run<DomSources, DomSinks>(
  (sources: Sources) => UI(sources), 
  (sinks: Sinks) => Dom(sinks)
)
```

**Comment by zimme** [comment]
Makes sense :+1:

**Comment by TylorS** [comment]
Let us know if we can be of any further help. Happy Motorcycling!
