### ISSUE TITLE
Curry isolate

### ISSUE THREAD

**Issue by Frikki** [motorcyclets/motorcycle#158]
At the time of this writing, [`isolate`](https://github.com/motorcyclets/motorcycle/blob/3585d22d10f6a78a46c5929d7ed901ad8f826b70/packages/mostly-dom/src/isolate.ts#L27) accepts two arguments: `component:Component<Sources, Sinks>` and `key:String`, respectfully. When dealing with a list of components that need isolation, it could be beneficial to be able to map over a list of keys. E.g.:

```typescript
const isolatedComponents = map(isolate(MyComponent), keys)
```

I will therefor propose that we curry the `isolate` function.

**Comment by TylorS** [comment]
:+1:

**Comment by Frikki** [comment]
After discussion elsewhere, we have agreed that adding `sources` as a third parameter is warranted now that `isolate` is curried.
