### ISSUE TITLE
Switch from 167 to @typed/prelude

### ISSUE THREAD

**Issue by TylorS** [motorcyclets/motorcycle#174]

**Comment by Frikki** [comment]
Let's find which packages need this upgrade, and create separate upgrade issues for each in order to minimize failure probabilities and have smaller PRs.

**Comment by TylorS** [comment]
`dom`, `mostly-dom`, and `stream` all need to be switched over

**Comment by TylorS** [comment]
Closing this issue in favor of #194 #195 and #196
