### ISSUE TITLE
Improve @motorcycle/run semantically

### ISSUE THREAD

**Issue by Frikki** [motorcyclets/motorcycle#189]
The current code, v4.1.0, explicitly mentions `UI` and `Application`, which is somewhat misleading and hints a specific architecture. Motorcycle's _only_ general suggestion, however, is to _separate pure functions from side effects_.

Instead of ...

```typescript
export function run<
  Sources extends Readonly<Record<string, any>>,
  Sinks extends Readonly<Record<string, Stream<any>>>
>(UI: Component<Sources, Sinks>, Application: EffectfulComponent<Sinks, Sources>)
```

... rename `UI` to `Main`, `Application` to `IO`, and `EffectfulComponent` to `IOComponent`.

Now, the main entry point to a Motorcycle application is `Main`, a regular component, and the side effects entry point is `IO`, an IO component, which by its name and type indicates side effects.

**Comment by TylorS** [comment]
👍
