### ISSUE TITLE
Renovate error: @motorcycle/types not found

### ISSUE THREAD

**Issue by rarkins** [motorcyclets/motorcycle#37]
Hi @TylorS,

I'm the author of the Renovate app/service. I wanted to alert you of an error I saw in my logs, that the dependency `@motorcycle/types` cannot be found.

It's referenced here: https://github.com/motorcyclets/motorcycle/blob/develop/packages/stream/package.json#L40

And it can't be found here: https://www.npmjs.com/package/@motorcycle/types

Unfortunately, this error means that Renovate can't update *any* of the packages in this `package.json`, the reason being: we choose not to update a `package.json` unless we can update its accompanying lock file, and we can only generate the lock file if `yarn` can install all modules.

Assuming it's a public module, you need to either remove it from the `package.json` or publish it to `npm` so that it can be found.

Let me know in case if I can help, or if I am misunderstanding anything.

**Comment by TylorS** [comment]
Hello @rarkins, 

Thanks for taking the time to write me. Currently `@motorcycle/types` is not published on npm. I'm currently waiting to complete some other packages before releasing them all publicly.

I'm brand new to using Renovate, and really excited to see how it works in a lerna monorepo. Let me know if I'm doing anything stupid in the mean time.

Thank you for your time and for Renovate!

**Comment by rarkins** [comment]
Thanks for the feedback. At least, now you're aware that your `packages/stream/package.json` won't get "renovated" until `@motorcycle/types` is published to npm.

Re: renovate approach, I'm happy to give advice but I also try for the tool to not be too opinionated like "you must update your packages THIS way". So, whatever works best for you is essentially the right way. I haven't actually coded anything specific for lerna, so let me know if the way it works out of the box ever seems cumbersome. I can then let you know if any existing configuration setting can fix that or if an enhancement is needed. 

An example might be if you want your own dependencies to be updated downstream "immediately" - and perhaps even automerged without your intervention - while you prefer all other dependencies to only be checked only weekly. This type of thing is possible but obviously would need configuration to override the default behaviour.

You can always reply in this issue, or raise an issue in the renovate repo, or simply @rarkins me if there's a particular issue or PR you want to point out as I should see it in my notifications.

**Comment by TylorS** [comment]
One cool thing about Lerna is when you publish a package all of the downstream packages get updated with the new upstream package version already (if they're in the monorepo). As for the other dependencies I'm happy with them updating as soon as renovate can. So far I haven't had any issues, it updated 3 dependencies in the root `/package.json`. The fact that it even tried to update `packages/stream/package.json` is a huge step up from GreenKeeper!

Thank you very much for you time, and for Renovate. I'll be sure to give any feedback as it comes!
